name: Build
description: |
  This is a build action.

inputs:
  git_ref:
    description: The branch, tag or SHA to checkout
    required:    true
    type:        string
  token:
    description: GitHub token used to checkout the repository
    required:    false
    type:        string
  aws_role_arn:
    description: AWS IAM role name for GitHub OIDC provider
    required:    true
    type:        string
  aws_region:
    description: AWS region for the ECR endpoint
    required:    false
    type:        string
    default:     us-east-1
  some_build_arg:
    description: This is some important build argument
    required:    true
    type:        string
  some_deploy_arg:
    description: This is some important deploy argument
    required:    true
    type:        string

outputs:
  registry:
    description: URL of the default registry
    value:       ${{ steps.build.outputs.registry }}
  endpoint_url:
    description: URL of the deployed endpoint
    value:       ${{ steps.deploy.outputs.endpoint_url }}

runs:
  using: composite
  steps:
    - name: Set secrets
      id:   secret
      run: |
        cat <<EOF
        ::add-mask::${{ inputs.token }}
        ::set-output name=token::${{ inputs.token }}
        EOF
      shell: bash
    - name: Build
      uses: rjeczalik/github-actions-example/.github/actions/build@master
      with:
        git_ref:        ${{ inputs.git_ref }}
        token:          ${{ steps.secret.outputs.token }}
        aws_role_arn:   ${{ inputs.aws_role_arn }}
        aws_region:     ${{ inputs.aws_region }}
        some_build_arg: ${{ inputs.some_build_arg }}
    - name: Deploy
      uses: rjeczalik/github-actions-example/.github/actions/deploy@master
      with:
        git_ref:         ${{ inputs.git_ref }}
        aws_role_arn:    ${{ inputs.aws_role_arn }}
        aws_region:      ${{ inputs.aws_region }}
        ecr_registry:    ${{ steps.build.outputs.registry }}
        some_deploy_arg: ${{ inputs.some_deploy_arg }}
